---
- name: Django Project Automation
  hosts: localhost
  gather_facts: no
  vars:
    dirpath: "{{ dirpath }}"
    project_name: "{{ project_name }}"

  tasks:
    - name: Check if directory path exists
      stat:
        path: "{{ dirpath }}"
      register: dir_check

    - name: Create directory path if not exists
      file:
        path: "{{ dirpath }}"
        state: directory
      when: dir_check.stat.exists == false

    - name: Check if the Django project exists
      stat:
        path: "{{ dirpath }}/{{ project_name }}"
      register: project_check

    - name: Install Django if not installed
      pip:
        name: django
        state: latest
      when: project_check.stat.exists == false

    - name: Create Django project if it doesn't exist
      command: django-admin startproject {{ project_name }}
      args:
        chdir: "{{ dirpath }}"
        creates: "{{ dirpath }}/{{ project_name }}/manage.py"
      when: project_check.stat.exists == false

    - name: Output project creation status
      debug:
        msg: "Django project {{ project_name }} is created at {{ dirpath }}"
      when: project_check.stat.exists == false

    - name: Output message if project exists
      debug:
        msg: "Django project {{ project_name }} already exists at {{ dirpath }}"
      when: project_check.stat.exists == true
