---
- name: Express Project Automation
  hosts: localhost
  gather_facts: no
  vars:
    dirpath: "{{ dirpath }}"
    project_name: "{{ project_name }}"

  tasks:
    - name: Check if directory path exists
      stat:
        path: "{{ dirpath }}"
      register: dir_check

    - name: Create directory path if not exists
      file:
        path: "{{ dirpath }}"
        state: directory
      when: dir_check.stat.exists == false

    - name: Check if the Express project exists
      stat:
        path: "{{ dirpath }}/{{ project_name }}"
      register: project_check

    - name: Create Express project directory if it doesn't exist
      file:
        path: "{{ dirpath }}/{{ project_name }}"
        state: directory
      when: project_check.stat.exists == false

    - name: Initialize npm project
      command: npm init -y
      args:
        chdir: "{{ dirpath }}/{{ project_name }}"
      when: project_check.stat.exists == false

    - name: Install Express.js
      command: npm install express
      args:
        chdir: "{{ dirpath }}/{{ project_name }}"
      when: project_check.stat.exists == false

    - name: Write Express server code into index.js
      copy:
        dest: "{{ dirpath }}/{{ project_name }}/index.js"
        content: |
          const express = require('express');
          const app = express();
          const port = 3000;

          app.get('/', (req, res) => res.send('Hello, World!'));

          app.listen(port, () => console.log('Server running on http://localhost:' + port));
      when: project_check.stat.exists == false

    - name: Output project creation status
      debug:
        msg: "Express project {{ project_name }} is created at {{ dirpath }}"
      when: project_check.stat.exists == false

    - name: Output message if project exists
      debug:
        msg: "Express project {{ project_name }} already exists at {{ dirpath }}"
      when: project_check.stat.exists == true
