---
- name: React Project Automation
  hosts: localhost
  gather_facts: no
  vars:
    dirpath: "{{ dirpath }}"
    project_name: "{{ project_name }}"

  tasks:
    - name: Check if directory path exists
      stat:
        path: "{{ dirpath }}"
      register: dir_check

    - name: Create directory path if not exists
      file:
        path: "{{ dirpath }}"
        state: directory
      when: dir_check.stat.exists == false

    - name: Check if the React project exists
      stat:
        path: "{{ dirpath }}/{{ project_name }}"
      register: project_check

    - name: Create React project if it doesn't exist
      command: npx create-react-app {{ dirpath }}/{{ project_name }}
      when: project_check.stat.exists == false
      args:
        creates: "{{ dirpath }}/{{ project_name }}/package.json"

    - name: Output project creation status
      debug:
        msg: "React project {{ project_name }} is created at {{ dirpath }}"
      when: project_check.stat.exists == false

    - name: Output message if project exists
      debug:
        msg: "React project {{ project_name }} already exists at {{ dirpath }}"
      when: project_check.stat.exists == true
